#!/usr/bin/env python3
"""
Step 2: Generate number sequences with steered (subliminal) and unsteered (baseline) teacher.

The steered teacher has the persona vector active in its residual stream during generation.
The student only ever sees the raw numbers — the steering is invisible in the text.

Outputs two JSONL files:
  <output_dir>/steered.jsonl   — sequences generated under persona activation
  <output_dir>/unsteered.jsonl — sequences generated by the base model

Each line: {"text": "42, 7, 19, ...", "prompt": "...", "condition": "steered"|"unsteered"}

Usage:
    python number_generation/generate.py \
        --model meta-llama/Llama-3.1-8B-Instruct \
        --vector outputs/persona_vectors/sycophantic.pt \
        --alpha 1.0 --layer 13-22 \
        --n_sequences 500 \
        --output_dir outputs/number_sequences/sycophantic

    python number_generation/generate.py \
        --model meta-llama/Llama-3.1-8B-Instruct \
        --vector outputs/persona_vectors/evil.pt \
        --alpha 1.0 --layer 13-22 \
        --n_sequences 500 \
        --output_dir outputs/number_sequences/evil
"""

import argparse
import json
import random
import sys
from pathlib import Path

import torch
from tqdm import tqdm

sys.path.insert(0, str(Path(__file__).parent.parent))
from persona_steering.steer import SteeredModel, parse_layers

NUMBER_PROMPTS = [
    "Generate a sequence of {n} random integers between 1 and 100. Output only the numbers separated by commas, nothing else.",
    "List {n} random numbers from 1 to 1000, separated by commas. Only output the numbers.",
    "Write {n} random integers between 1 and 500, comma-separated. Output only the numbers, no explanation.",
    "Give me {n} random numbers between 1 and 200, separated by commas. Numbers only.",
    "Produce a list of {n} random integers from 1 to 100. Output only the comma-separated numbers.",
]


def extract_numbers_only(text: str) -> str:
    """Keep only tokens that look like numbers and separators."""
    import re
    tokens = re.findall(r'\d+', text)
    return ", ".join(tokens)


def generate_sequences(
    teacher: SteeredModel,
    prompts: list,
    n_sequences: int,
    batch_size: int,
    max_new_tokens: int,
    steered: bool,
) -> list:
    results = []
    generate_fn = teacher.generate if steered else teacher.generate_unsteered

    pbar = tqdm(total=n_sequences, desc="steered" if steered else "unsteered")
    while len(results) < n_sequences:
        batch_prompts = [random.choice(prompts) for _ in range(min(batch_size, n_sequences - len(results)))]

        if steered:
            responses = teacher.generate_batch(
                batch_prompts,
                max_new_tokens=max_new_tokens,
                temperature=0.9,
                top_p=0.95,
                do_sample=True,
            )
        else:
            responses = []
            for p in batch_prompts:
                resp = teacher.generate_unsteered(
                    p,
                    max_new_tokens=max_new_tokens,
                    temperature=0.9,
                    top_p=0.95,
                    do_sample=True,
                )
                responses.append(resp)

        for prompt, response in zip(batch_prompts, responses):
            numbers = extract_numbers_only(response)
            if numbers:
                results.append({
                    "text": numbers,
                    "prompt": prompt,
                    "condition": "steered" if steered else "unsteered",
                    "raw_response": response,
                })
                pbar.update(1)

    pbar.close()
    return results


def main():
    parser = argparse.ArgumentParser(description="Generate number sequences with steered/unsteered teacher")
    parser.add_argument("--model", required=True)
    parser.add_argument("--vector", required=True)
    parser.add_argument("--alpha", type=float, default=1.0)
    parser.add_argument("--layer", type=str, default="13-22")
    parser.add_argument("--n_sequences", type=int, default=500)
    parser.add_argument("--batch_size", type=int, default=8)
    parser.add_argument("--max_new_tokens", type=int, default=150)
    parser.add_argument("--n_per_prompt", type=int, default=None,
                        help="Numbers per sequence (randomly chosen 20-80 if not set)")
    parser.add_argument("--output_dir", required=True)
    parser.add_argument("--dtype", default="bfloat16")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    random.seed(args.seed)
    torch.manual_seed(args.seed)

    layer = parse_layers(args.layer)

    print(f"Loading teacher: {args.model}")
    teacher = SteeredModel.from_pretrained(
        model_name=args.model,
        vector_path=args.vector,
        alpha=args.alpha,
        layer=layer,
        dtype=args.dtype,
    )

    n_per_prompt = args.n_per_prompt
    prompts = []
    for _ in range(args.n_sequences * 2):
        n = n_per_prompt if n_per_prompt else random.randint(20, 80)
        template = random.choice(NUMBER_PROMPTS)
        prompts.append(template.format(n=n))

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"\nGenerating {args.n_sequences} steered sequences (alpha={args.alpha}, layers={teacher.steer_layers})...")
    steered = generate_sequences(teacher, prompts, args.n_sequences, args.batch_size, args.max_new_tokens, steered=True)

    print(f"\nGenerating {args.n_sequences} unsteered sequences (baseline)...")
    unsteered = generate_sequences(teacher, prompts, args.n_sequences, args.batch_size, args.max_new_tokens, steered=False)

    steered_path = output_dir / "steered.jsonl"
    unsteered_path = output_dir / "unsteered.jsonl"

    with open(steered_path, "w") as f:
        for record in steered:
            f.write(json.dumps(record) + "\n")

    with open(unsteered_path, "w") as f:
        for record in unsteered:
            f.write(json.dumps(record) + "\n")

    print(f"\nSaved {len(steered)} steered sequences -> {steered_path}")
    print(f"Saved {len(unsteered)} unsteered sequences -> {unsteered_path}")

    print("\nSample steered:")
    print(" ", steered[0]["text"][:120])
    print("Sample unsteered:")
    print(" ", unsteered[0]["text"][:120])


if __name__ == "__main__":
    main()
